language: node_js
node_js:
  - lts/*
branches:
  only:
    - master
cache:
  # cache global npm modules
  directories:
    - $HOME/.npm-cache
script:
  # run the respec2html utility
  # if successful, replace the source index.html with the generated one & clean up
  - echo "Building the ReSpec page"
  - npx -p respec respec2html -s index.html?githubtoken=$GITHUB_PAGES_AUTH -o build-index.html && echo "Build OK. Cleaning up" && rm index.html && mv build-index.html index.html
  # Note: We may need to add a GitHub token to the ReSpec config to avoid rate limiting
deploy:
  # publish as a commit to the gh-pages branch
  skip_cleanup: true
  keep_history: true
  provider: pages
  github_token: $GITHUB_PAGES_AUTH
# after_failure:
  # create a GH issue?