language: node_js
node_js:
  - lts/*
branches:
  only:
    - master
cache:
  # cache global npm modules
  directories:
    - $HOME/.npm-cache
script:
  # run the respec2html utility
  # if successful, replace the source index.html with the generated one & clean up
  - npx -p respec respec2html -s index.html?githubToken=$GITHUB_PAGES_AUTH -o build-index.html && rm index.html && mv build-index.html index.html
deploy:
  # publish as a commit to the gh-pages branch
  skip_cleanup: true
  keep_history: true
  provider: pages
  github_token: $GITHUB_PAGES_AUTH
# after_failure:
  # create a GH issue?
